language: node_js
node_js:
- 9.2.0
- 9.0.0
deploy:
  provider: npm
  email: dev@knowre.com
  api_key:
    secure: lzL2Y+CvkjFHUN7PPCERyUdHDShNqb/0wWvdempEItU7SF0oFtuIguXH+eOr64+fvBR16UEPDs3yguMp9IHbQOpugDYHo5AzApYthJxXkw0pskqX4WphywjuJbXNyeqSK4IjMpfAGJ3hD5DOb1gc8UN3I+40Bk6zCcdI5D/99Uka6JaO+z1xZ2OEz9qKr+cPfZvD6nvmqxUE+LJ2QK9F04BMk2rJx/kRJ3t5QkO71La+AkWFMjd4rZXT3EilCxl/xg9R2lINMtvAe8LU4k565N2Ot4oCwCkCdQxP7apyX1tR80H2BjqvQxHkbHnUgve9MtgBSkPZ6jGcOf+V7LKX5iXLUe9Amgi0Bm8EUFM/aFkV+F7sYTnEqjH2N3Dk6Zs4NjyZIAFBpXDx+yW4s2dvX7vtPlbFzUt6CMOBw8WQJetHtcaSdWb1MUmReD26GYnGCpi0mnCch07hD81rVo+lJ/+cX0dn91wr9Bff2bP/EtVRk7gFvS65jU4YyiZ8ctY4wbTxrL36t8JnynrehAjQD24H7MZtSDKLVE8mLWItEi403TeQ8hNvo8DTfkLoSzPs64SCedMEJFIquc+VARECtQpIDE7X+2PaJsDTahMK8gec/El8AAmZB7sQLr/I8DbaGCHXthW1d39JU6nTX5vIEiXLlwgDQTcrE7Mu04NhFNI=
  on:
    branch: stable
    node_js: 9.2.0
notifications:
  slack:
    secure: YjGsVEVSs8d5+7PCrZzHinVr4kEqyDtq/3HhPs+jCQT+g3O8c8axPKEXFQW2cHKsrShxwFmZ01uyieQwOgfhQsrmOQSaYc05KADWBqxjqycQO6ctS1aQPsfw3CCdWu3D6JYphTuAG1Q/5ppVQlKtMU8DGgu4adQZFHimqXUYUeE2TmV/OIBVyaegFR/cHGyjWPeLv6yhTvlnQl1KsIiRHqi2bPiKVBYVjKhBX6EwwsMHtKj2y+CgmRk+0fBzE6m/1hN69KRCRQ3wTLQvLgfuQ3KFrWB681sUZD9IvJdVRS68AqvoZBLuVkoBRN8Fan1gPD7rHdtLR9YmMNWcuyRZFqJ2f0I0pzxL8Q8zqgg6XiZ/Z7/Ri6vdWz+wPHINcLCk+geSP0Fk5wziPXcSDs/R7WO78KkO2DaepzUmWBhzyHIXL+lYlAjy7gsRE928TGte9TCtDexrXTGW8Vw5FdCJG77xME511aiGiRzHDiSMdoPHUnUXkjP1WxqcQmOoaEieO19ctqEvfEV/0xMNZVaNSQCLF4D2v98ax7GYFc83y78Tywd2egQoLpPt2PLDBMkp8x9DPAjquL2nQSAaYQEubss/kCSLh7mWPQQH3g4Evz0xSBXEUuEe4A+hyF+P9RJTE5D0+WH/1YEdNLvlzT0Q/wtG1Dv3xNqyBBb6H3By6d0=
env:
  matrix:
    secure: eRT1TTYmOHeOne79q6xHncpnp2vtc/JWSdpLkoxzl6cyHaaqpUTRDs6TlT71L5y7G+rpXZ/2EMbkol4qKjQATj+VfioC9x2SAjL3VNinttUpNyp1NV70+nxLBB1DsceOP1e7IY4hEKCz6iYqU7/ORBTH2VEtnMbD85Lk8wOikpVPCCj5X2KM6o7JuvFLHg3h1NvMBJ4bwocxRi1fWaZhWaCYxsUUwkMQGt6YiRlxvzJSk71ApdWkRPKbdXUUxcYFiv/X7uNpXGcukS4G3BqrpbiqEawOelWwgxgcff+rm+LPMy2Tl/8AqNEzWvrbrKkcLtccGX/K34/bf4LrPyBRUK2wr1lBgChGTagr8L0jULjrQHQM0JN0FP2LYLPsmg29P+UizdHV6hEnSZ7X0/MZ/8NyAPx8Mqpfiu42S/+IB5TgVHOacEwjyDHTYrIgNHg0/8etIhtepEhaRLhjFAb6heqVQqD5ALJQTkHdftr2M8FVXKtp9BI4uBCInwaxyDpPaNCrrY3hpiR1U3f8AX2TJYJxncGUnmHb92OuYCDzVdX4llOxmfKuxgBOkKAT7X+fYa8szWlbi52EE1+Qpo1qtahCGgokRGl6WaWqAcdGV/avTSD2CSk2vSCjIuQaoS2CSikSvrNwUtaIf1QwwDie7Dkn2Yj3D53wjwhJxUnRA0E=
